### ISSUE TITLE
关于硬件问题

### ISSUE THREAD

**Issue by micele00l** [hx23840/YunDo#1]
求问项目中的硬件是直接按原仓库里的epro文件打板的吗？我从嘉立创打板后测量有地方(C10, C11, C2)短路，请问在YunDo这个项目中硬件上是否有别的改动？

**Comment by hx23840** [comment]
是的，我在嘉立创打板的，没遇见您说的情况

**Comment by micele00l** [comment]
感谢，那我再排查一下板子

**Comment by micele00l** [comment]
抱歉再打扰你，我确定了嘉立创发来的6张板子上都是3v3对地短路，请问您那边是否有多余的板子能给我一张做个参考？
![SCR-20240608-stri](https://github.com/hx23840/YunDo/assets/4356266/299cf055-bc0d-497c-8bb5-023bfe4526ed)

**Comment by hx23840** [comment]
> 抱歉再打扰你，我确定了嘉立创发来的6张板子上都是3v3对地短路，请问您那边是否有多余的板子能给我一张做个参考？ ![SCR-20240608-stri](https://private-user-images.githubusercontent.com/4356266/337878010-299cf055-bc0d-497c-8bb5-023bfe4526ed.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTQ5MzIsIm5iZiI6MTcxNzg1NDYzMiwicGF0aCI6Ii80MzU2MjY2LzMzNzg3ODAxMC0yOTljZjA1NS1iYzBkLTQ5N2MtOGJiNS0wMjNiZmU0NTI2ZWQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDEzNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYWRjMzEyOGIzMmMyNTA5NThkZTNiNzY1MjBmOWUzZGY3OTliZTJjYWUyMzU4MjhmNmI2NDQ4NTg4NGQzN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hkPKdkmkYvqDrW9JcQfSkQgf-vRx7SWUvqwiw-HknQM)

硬件的原作者在b站有视频教程说明，可以参考， [链接](https://www.bilibili.com/video/BV1ku4m1g7vA/?spm_id_from=333.999.0.0&vd_source=d61f4ed1f86cdec9e1d118080d758f70)

**Comment by micele00l** [comment]
> > 抱歉再打扰你，我确定了嘉立创发来的6张板子上都是3v3对地短路，请问您那边是否有多余的板子能给我一张做个参考？ ![SCR-20240608-stri](https://private-user-images.githubusercontent.com/4356266/337878010-299cf055-bc0d-497c-8bb5-023bfe4526ed.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTQ5MzIsIm5iZiI6MTcxNzg1NDYzMiwicGF0aCI6Ii80MzU2MjY2LzMzNzg3ODAxMC0yOTljZjA1NS1iYzBkLTQ5N2MtOGJiNS0wMjNiZmU0NTI2ZWQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDEzNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYWRjMzEyOGIzMmMyNTA5NThkZTNiNzY1MjBmOWUzZGY3OTliZTJjYWUyMzU4MjhmNmI2NDQ4NTg4NGQzN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hkPKdkmkYvqDrW9JcQfSkQgf-vRx7SWUvqwiw-HknQM)
> 
> 硬件的原作者在b站有视频教程说明，可以参考， [链接](https://www.bilibili.com/video/BV1ku4m1g7vA/?spm_id_from=333.999.0.0&vd_source=d61f4ed1f86cdec9e1d118080d758f70)

好的，我再看看
